version: '3.3'

services:
  server:
    container_name: dockert-server
    build: .
    restart: always
    ports:
      - 8000:5000
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
    depends_on:
      - database

  database:
    container_name: dockert-db
    image: postgres:alpine
    restart: always
    ports:
      - 5430:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker_tutor
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
#
# networks:
#   dtutor-net:
